WIP query
bugto solve because of tankstack

Error: Only plain objects, and a few built-ins, can be passed to Client Components from Server Components. Classes or null prototypes are not supported.

https://tanstack.com/query/latest/docs/framework/react/guides/advanced-ssr
https://stackoverflow.com/questions/78118174/err-only-plain-objects-and-a-few-built-ins-can-be-passed-to-client-components